add a separate cdylib crate

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -257,20 +257,34 @@ jobs:
         with:
           toolchain: stable
           targets: ${{matrix.target}}
-      - name: Rust cache
-        uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8
-        with:
-            shared-key: "stable-${{matrix.target}}"
-      - name: get zpipe.c
-        run: wget https://www.zlib.net/zpipe.c
-      - name: cargo build
-        run: cargo build --target ${{matrix.target}} -p libz-rs-sys --release
-      - name: cc
-        run: cc -o zpipe zpipe.c target/${{matrix.target}}/release/deps/liblibz_rs_sys.so
-      - name: execute
-        run: cat Cargo.toml | ./zpipe | ./zpipe -d > out.txt
-      - name: compare
-        run: cmp -s Cargo.toml out.txt
+      - name: "cdylib: default settings"
+        working-directory: libz-rs-sys-cdylib
+        run: |
+          cargo build --release --target ${{matrix.target}}
+          cc -o zpipe zpipe.c target/${{matrix.target}}/release/deps/libz_rs.so
+          ./zpipe < Cargo.toml | ./zpipe -d > out.txt
+          cmp -s Cargo.toml out.txt
+      - name: "cdylib: rust-allocator"
+        working-directory: libz-rs-sys-cdylib
+        run: |
+          cargo build --release --target ${{matrix.target}} --no-default-features --features="rust-allocator"
+          cc -o zpipe zpipe.c target/${{matrix.target}}/release/deps/libz_rs.so
+          ./zpipe < Cargo.toml | ./zpipe -d > out.txt
+          cmp -s Cargo.toml out.txt
+      - name: "cdylib: no_std"
+        working-directory: libz-rs-sys-cdylib
+        run: |
+          cargo build --release --target ${{matrix.target}} --no-default-features
+          cc -o zpipe_no_std zpipe_no_std.c target/${{matrix.target}}/release/deps/libz_rs.so
+          ./zpipe_no_std < Cargo.toml | ./zpipe_no_std -d > out.txt
+          cmp -s Cargo.toml out.txt
+      - name: "cdylib: custom-prefix"
+        working-directory: libz-rs-sys-cdylib
+        env:
+          LIBZ_RS_SYS_PREFIX: "MY_CUSTOM_PREFIX_"
+        run: |
+          cargo build --release --target ${{matrix.target}} --features=custom-prefix
+          objdump -tT target/${{matrix.target}}/release/deps/libz_rs.so | grep -q "MY_CUSTOM_PREFIX_uncompress" || (echo "symbol not found!" && exit 1)
 
   miri:
     name: "Miri"
@@ -285,8 +299,8 @@ jobs:
         uses: taiki-e/install-action@56ab7930c591507f833cbaed864d201386d518a8
         with:
           tool: cargo-nextest
-      - name: Test public C api with NULL arguments 
+      - name: Test public C api with NULL arguments
         run: "cargo +nightly miri nextest run -j4 -p test-libz-rs-sys null::"
         env:
           RUSTFLAGS: "-Ctarget-feature=+avx2"
-          MIRIFLAGS: "-Zmiri-tree-borrows" 
+          MIRIFLAGS: "-Zmiri-tree-borrows"
